<?php

namespace AppBundle\Repository;

/**
 * ChoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChoiceRepository extends \Doctrine\ORM\EntityRepository
{
}
