<?php

namespace AppBundle\Repository;

/**
 * HealthtipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HealthtipRepository extends \Doctrine\ORM\EntityRepository
{
}
