<?php

namespace AppBundle\Repository;

/**
 * HealthtipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HealthtipRepository extends \Doctrine\ORM\EntityRepository
{
    public function retreiveByAge($age)
    {
        if (is_null($age)) {
            return null;
        }
        $qb = $this->createQueryBuilder('ht')
                   ->where('ht.minAge <= :age')
                   ->Andwhere('ht.maxAge > :age')
                   ->setParameter('age', $age);
        $query = $qb->getQuery();

        return $query->getResult();
    }
}
