<?php

namespace AppBundle\Repository;

/**
 * UserSurveyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserSurveyRepository extends \Doctrine\ORM\EntityRepository
{
}
